/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Resolvers_Resolver */

#ifndef _Included_Resolvers_Resolver
#define _Included_Resolvers_Resolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Resolvers_Resolver
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Resolvers_Resolver_Add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Resolvers_Resolver
 * Method:    Query
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Resolvers_Resolver_Query
  (JNIEnv *, jobject);

/*
 * Class:     Resolvers_Resolver
 * Method:    QueryObject
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_Resolvers_Resolver_QueryObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
